apiVersion: v1
kind: Service
metadata:
  name: {{  .Values.appName }}
  labels:
    app: {{  .Values.appName }}
spec:
  ports:
  - port: {{ .Values.port }}
    targetPort: http
  selector:
    app: {{  .Values.appName }}
